stages:
    - build_gcc

.build_gcc:
  tags:
    - darwin-slurm-shared
    - batch
    - jacamar
    - yellow 
    - darwin
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://lisdi-git.lanl.gov/
  variables:
    #GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME/job_$CI_JOB_ID'
    GIT_SUBMODULE_STRATEGY: recursive
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug"
  stage: build_gcc
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - module load miniconda3
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - echo ${DEFINES}
    - module load gcc/11.2.0
    - module load cmake/3.29.2
    - module load cuda/11.6
    - module load openmpi/4.1.2-gcc_11.2.0
    - module load hdf5
    - j="$(grep -c processor /proc/cpuinfo 2>/dev/null)" || j=0; ((j++))
    - build_dir=build-${CI_JOB_NAME}-${CI_JOB_ID}
    - mkdir -p ${build_dir}
    - pushd ${build_dir}
      #- CXX=/mnt/local/ssd/vpic/kokkos/bin/nvcc_wrapper cmake -DCMAKE_PREFIX_PATH=/mnt/local/ssd/vpic/kokkos/build_gpu/install ..
    - cmake
      -DBUILD_INTERNAL_KOKKOS=ON
      -DENABLE_KOKKOS_CUDA=OFF
      -DENABLE_INTEGRATED_TESTS=ON
      -DENABLE_UNIT_TESTS=ON
      -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
      -DVPIC_ENABLE_HDF5=ON
      ${DEFINES:+${DEFINES}}
      ..
    - make -j ${j} -l ${l} VERBOSE=1
    - pip install numpy h5py
    - make test CTEST_OUTPUT_ON_FAILURE=1
    - make install DESTDIR=${PWD}/install
      #TODO: set OMP_PROC_BIND=spread and OMP_PLACES=threads (or similar)

.gcc:
  variables:
    _CXX: "g++"
  extends: .build_gcc

Release-GCC:
  variables:
    CMAKE_BUILD_TYPE: "Release"
    DEFINES: "-DVPIC_KOKKOS_DEBUG=OFF"
  extends: .gcc

Debug-GCC:
  variables:
    CMAKE_BUILD_TYPE: "Debug"
    DEFINES: "-DVPIC_KOKKOS_DEBUG=ON"
  extends: .gcc
