#! /usr/bin/env bash

H5Proot=~/H5Part-1.6.6-intel-17.0.4-openmpi-2.1.2/
HDF5ROOT=$HDF5_ROOT

deck=`echo $1 | sed 's,\.cxx,,g;s,\.cc,,g;s,\.cpp,,g;s,.*\/,,g'`

echo "/usr/projects/hpcsoft/toss3/grizzly/openmpi/3.1.6-intel-19.1.3/bin/mpiCC  -g -O3 -inline-forceinline -qoverride-limits -no-ansi-alias -Winline -qopt-report=5 -qopt-report-phase=all -diag-disable 10397 -Wl,--export-dynamic -I. -I/users/arile/vpic-hybrid/vpic-quad-hdf5/src -std=c++11  -DINPUT_DECK=$1 /users/arile/vpic-hybrid/vpic-quad-hdf5/deck/main.cc /users/arile/vpic-hybrid/vpic-quad-hdf5/deck/wrapper.cc -I${H5Proot}/include -I${HDF5ROOT}/include -o $deck.Linux -Wl,-rpath,/users/arile/vpic-hybrid/vpic-quad-hdf5/build -L/users/arile/vpic-hybrid/vpic-quad-hdf5/build -lvpic -lpthread -ldl -L${H5Proot}/lib -L${HDF5ROOT}/lib -lH5Part -lhdf5 -lz -DPARALLEL_IO"

/usr/projects/hpcsoft/toss3/grizzly/openmpi/3.1.6-intel-19.1.3/bin/mpiCC  -g -O3 -inline-forceinline -qoverride-limits -no-ansi-alias -Winline -qopt-report=5 -qopt-report-phase=all -diag-disable 10397 -Wl,--export-dynamic -I. -I/users/arile/vpic-hybrid/vpic-quad-hdf5/src -std=c++11  -DINPUT_DECK=$1 /users/arile/vpic-hybrid/vpic-quad-hdf5/deck/main.cc /users/arile/vpic-hybrid/vpic-quad-hdf5/deck/wrapper.cc -I${H5Proot}/include -I${HDF5ROOT}/include  -o $deck.Linux -Wl,-rpath,/users/arile/vpic-hybrid/vpic-quad-hdf5/build -L/users/arile/vpic-hybrid/vpic-quad-hdf5/build -lvpic -lpthread -ldl -L${H5Proot}/lib -L${HDF5ROOT}/lib -lH5Part -lhdf5 -lz -DPARALLEL_IO
