# Define shell
SHELL = csh

# Directory of precompiled VPIC libraries:
PROJECTDIR = /project/projectdirs/ntrain7/hybridVPIC/build-haswell/bin

all:
	${PROJECTDIR}/vpic pcai.cxx	

cleanall: 	
#	cd translate; make clean 
	-rm data/*
	-rm -rf hydro
	-rm -rf particle
	-rm -rf restart*
	-rm *.Linux
	-rm *.bin
	-rm *.vpc
	-rm *.btr
	-rm -rf rundata
	-rm -rf window
	-rm -rf fields
	-rm -rf spectrum
	-rm energy_spectrum
	-rm *.cy
	-rm *.op
	-rm *.ppu
	-rm outfile
	-rm info
	-rm *.eps
	-rm *.mpg
	-rm core.*
	-rm *~









