#! /usr/bin/env bash
#~----------------------------------------------------------------------------~#
# placeholder
#~----------------------------------------------------------------------------~#

#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

src_dir="${0%/*}/.."

#------------------------------------------------------------------------------#
# Check required environment variables
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

# The flag -rdynamic removes warnings of the form:
# Unable to find a safely writable symbol that corresponds to address 432af0
# (the closest match was "(null)" from "./lpi_2d_F6_test.Linux").  Writing out
# the raw address instead and keeping my fingers crossed.

cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_INTEGRATED_TESTS=ON \
  -DENABLE_UNIT_TESTS=ON \
  -DBUILD_INTERNAL_KOKKOS=ON \
  -DKokkos_ARCH_ZEN2=ON \
  -DKokkos_ENABLE_PTHREAD=OFF \
  -DKokkos_ENABLE_OPENMP=ON \
  -DCMAKE_CXX_FLAGS="-g -O2 -rdynamic" \
  $src_dir

#------------------------------------------------------------------------------#
# vim: syntax=sh
#------------------------------------------------------------------------------#

#~---------------------------------------------------------------------------~-#
# placeholder
#~---------------------------------------------------------------------------~-#
