#! /usr/bin/env bash
#~----------------------------------------------------------------------------~#
# placeholder
#~----------------------------------------------------------------------------~#

#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

src_dir="${0%/*}/.."

#------------------------------------------------------------------------------#
# Check required environment variables
#------------------------------------------------------------------------------#

#module purge
#module load PrgEnv-gnu
#module load cmake cuda cpe-cuda
COMPILER_VENDOR=gcc
COMPILER_VERSION=11.2.0
module load git cmake cuda/11.6 openmpi/4.1.2-${COMPILER_VENDOR}_${COMPILER_VERSION}
module list 2>&1 | tee modules.txt

#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

# The flag -rdynamic removes warnings of the form:
# Unable to find a safely writable symbol that corresponds to address 432af0
# (the closest match was "(null)" from "./lpi_2d_F6_test.Linux").  Writing out
# the raw address instead and keeping my fingers crossed.

# In the Cray environment, there is a bit of confusion about compilers and
# wrappers and such.  I've worked around it with some ad hoc CMake magic, but
# this line might be helpful when troubleshooting (run it when compiling user
# decks too).
#export NVCC_WRAPPER_DEFAULT_COMPILER=$(which CC)
export KOKKOS_PATH=/usr/projects/maehem/packages/packages-06-19-2024/installs/gpu/gcc-11.2.0/openmpi-4.1.2/kokkos-4.0.01-openmp-4.5-cuda-11.6-debug

export NVCC_WRAPPER=$KOKKOS_PATH/bin/nvcc_wrapper


CRAYPE_LINK_TYPE=dynamic cmake \
  -DCMAKE_BUILD_TYPE=Debug \
  -DENABLE_INTEGRATED_TESTS=ON \
  -DENABLE_UNIT_TESTS=ON \
  -DBUILD_INTERNAL_KOKKOS=OFF \
  -DENABLE_KOKKOS_CUDA=ON \
  -DCMAKE_PREFIX_PATH=${KOKKOS_PATH} \
  -DCMAKE_CXX_COMPILER=${NVCC_WRAPPER} \
  -DCMAKE_CXX_FLAGS="-g -rdynamic"\
  $src_dir

#------------------------------------------------------------------------------#
# vim: syntax=sh
#------------------------------------------------------------------------------#

#~---------------------------------------------------------------------------~-#
# placeholder
#~---------------------------------------------------------------------------~-#
