#! /usr/bin/env bash
#~----------------------------------------------------------------------------~#
# placeholder
#~----------------------------------------------------------------------------~#

#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

src_dir="${0%/*}/.."

#------------------------------------------------------------------------------#
# Check required environment variables
#------------------------------------------------------------------------------#

#module purge
module load PrgEnv-gnu
module load cmake cudatoolkit cpe-cuda
#module list 2>&1 | tee modules.txt

#------------------------------------------------------------------------------#
# Choose support for HDF5 output for fields and hydro
#------------------------------------------------------------------------------#
# If SET_HDF5=OFF, the output of fields and hydro are in binary format.
# If SET_HDF5=ON, the output of fields and hydro are in HDF5 format.
#------------------------------------------------------------------------------#
SET_HDF5="OFF"
if [ "$SET_HDF5" = "ON" ]
then
    module load cray-hdf5-parallel
fi
module list 2>&1 | tee modules.txt


#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

# The flag -rdynamic removes warnings of the form:
# Unable to find a safely writable symbol that corresponds to address 432af0
# (the closest match was "(null)" from "./lpi_2d_F6_test.Linux").  Writing out
# the raw address instead and keeping my fingers crossed.

# In the Cray environment, there is a bit of confusion about compilers and
# wrappers and such.  I've worked around it with some ad hoc CMake magic, but
# this line might be helpful when troubleshooting (run it when compiling user
# decks too).
#export NVCC_WRAPPER_DEFAULT_COMPILER=$(which CC)

CRAYPE_LINK_TYPE=dynamic /usr/projects/maehem/packages/cmake-3.29.9/build/bin/cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_INTEGRATED_TESTS=ON \
  -DENABLE_UNIT_TESTS=ON \
  -DBUILD_INTERNAL_KOKKOS=ON \
  -DENABLE_KOKKOS_CUDA=ON \
  -DKokkos_ENABLE_CUDA=ON \
  -DKokkos_ARCH_AMPERE80=ON \
  -DKokkos_ARCH_ZEN2=ON \
  -DKokkos_ENABLE_PTHREAD=OFF \
  -DKokkos_ENABLE_OPENMP=ON \
  -DCMAKE_CXX_COMPILER="CC" \
  -DCMAKE_CXX_FLAGS="-g -rdynamic "\
   -DVPIC_ENABLE_HDF5=${SET_HDF5} \
  $src_dir

#------------------------------------------------------------------------------#
# vim: syntax=sh
#------------------------------------------------------------------------------#

#~---------------------------------------------------------------------------~-#
# placeholder
#~---------------------------------------------------------------------------~-#
