#!/bin/bash
#SBATCH -t 12:00:00    # walltime
#SBATCH -N 4 # number of cluster nodes
#SBATCH -n 128 # number of MPI ranks / slurm tasks
#SBATCH -o job-%j.out # pathname of stdout file
#SBATCH -e job-%j.err # pathname of stderr file, using job and first node values
#SBATCH -J mirror2d
#SBATCH -A w25_maehem

###SBATCH -p gpu
###SBATCH --reservation=gpu
###SBATCH -A w25_maehem_g

##### These are shell commands
date

srun -n 128 ./mirror_nbi_2d.Linux >& outfile

date
echo 'Done'