#!/bin/bash
#SBATCH -t 12:00:00    # walltime
#SBATCH -N 4 # number of cluster nodes
#SBATCH -n 4 # number of MPI ranks / slurm tasks
#SBATCH -o slurm.out # pathname of stdout file
#SBATCH -e slurm.err # pathname of stderr file, using job and first node values
#SBATCH -J mirror2d
# SBATCH -A w25_maehem

##### These are shell commands
date

cd /vast/home/cgraham/vpic-kokkos/
module load gcc/12.2.0 openmpi/4.1.5-gcc_12.2.0 cmake/3.29.2 cuda/12.9.1
export NVCC_WRAPPER_DEFAULT_COMPILER=mpicxx
mkdir build
cd build
bash ../arch/Darwin_Ampere
srun -n 4 ../examples/mirror-cyl/mirror_RZ.Linux >& outfile

date
echo 'Done'