#!/bin/bash
#SBATCH -t 6:00:00     # walltime,
#SBATCH -N 4           # number of cluster nodes
#SBATCH -n 4          # number of MPI ranks / Slurm tasks
#SBATCH -o slurm.out # pathname of stdout file
#SBATCH -e slurm.err # pathname of stderr file, using job and first node values
#SBATCH -J mir
#SBATCH -p volta-x86
# load modulefiles
module load gcc openmpi

# run the app
cd /vast/home/cgraham/vpic-kokkos/
module load gcc/12.2.0 openmpi/4.1.5-gcc_12.2.0 cmake/3.29.2 cuda/12.9.1
export NVCC_WRAPPER_DEFAULT_COMPILER=mpicxx
mkdir build
cd build
bash ../arch/Darwin_Ampere
srun -n 4 /vast/home/cgraham/vpic-kokkos/build/mirror_RZ_cyl.Linux
##--restore restart0/restart.0  >& outfile2 