#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Read trajectory data generated by monopole test
data = np.loadtxt("../../../build/monopole_trajectory.txt")

step = data[:, 0]
# positions
x = data[:, 1]
y = data[:, 2]
z = data[:, 3]
ux = data[:, 4]
uy = data[:, 5]
uz = data[:, 6]

# 3D trajectory plot
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')
ax.plot(x, y, z, 'b-', linewidth=1, alpha=0.7)
ax.scatter([x[0]], [y[0]], [z[0]], color='g', s=50, label='Start')
ax.scatter([x[-1]], [y[-1]], [z[-1]], color='r', s=50, label='End')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
ax.set_title('Monopole Particle Trajectory (3D)')
ax.legend()
plt.tight_layout()
plt.savefig('monopole_trajectory.png', dpi=150)
print('Saved monopole_trajectory.png')
plt.show()
